### PR TITLE
Try Catch blocks for every controller

### LINKED ISSUE #1: Routes are not protected from bugs
There is a need to put every route in try-catch block , because right now the data is just assumed to be always fetched, there is a need of error handling to avoid server getting down.

### PR DESCRIPTION
**Pull request by priyanshu20**
fixes #1 

Added a try catch block for all controllers, this prevents app form crashing whenever an error occurs.

### CODE REVIEW

**Comment by priyanshu20** [comment]
@ArunTeltia please review

**Comment by ArunTeltia** [comment]
Indentation please and instead of consoling those error can we just work on what king of error we can get from it even the comment about the type of error can help, This looks good to me for right now but this also needs to be addressed, for now lets focus on the indentation of the code. @priyanshu20 please have a look

**Comment by priyanshu20** [comment]
@ArunTeltia 
* for the indentation I made a commit
* for error types , I think there are a lot of error types per controller, how do I classify them ? according to me there would have to be 5-6 if blocks per controller as there are multiple errors that can occur

**Review by singhayushh — COMMENTED** [review]
Instead of just logging the error, would it not be better to render the error page?

**Comment by priyanshu20** [comment]
@singhayushh I did that in the first commit but realized that in the existing codebase almost everywhere  errors are logged , rather than rendered. 
So I removed the res.render

**Comment by ArunTeltia** [comment]
@singhayushh It will not give the error page it will just send back the call with nothing inside it and the frontend that would been expecting some data will not recieve any data and the data will not get render 
this is better then breaking the server and restarting it after breaking it 
As restart of the server consume resources(thinking of an AWS instance or GCP instance )
Anyway that will be the great start on knowing how many types of error one can get and then if somehow we get those errors how can we make our frontend behave

**Comment by ArunTeltia** [comment]
> @ArunTeltia
> 
> * for the indentation I made a commit
> * for error types , I think there are a lot of error types per controller, how do I classify them ? according to me there would have to be 5-6 if blocks per controller as there are multiple errors that can occur

Lets focus on one route and work on the number of issues a route can get whether the fetch api we are using can recieve 404 error or something 
We want to know what error we can get from those api
@priyanshu20

**Review by ArunTeltia — APPROVED** [review]
Looks good to me for now @LordShenron merge these changes

**Pull request merged**
