### PR TITLE
Project restructuring with separate controllers and utils directories

### PR DESCRIPTION
**Pull request by singhayushh**
This PR is a fix for issues #2 and #7 

```
Change log:
- Routes for different features (as listed below) have been moved to separate sub directories under routes/
    - loader
    - manga
    - search
    - anime streaming 
- Modules for handling each end point have been created under controllers/
```

None of the functions of the code have been modified, the functions have just been refactored to make the development more efficient and maintainable.

### CODE REVIEW

**Comment by ArunTeltia** [comment]
Is this PR review ready @singhayushh or some more commits needed ?

**Comment by singhayushh** [comment]
I hope this is Review Ready as I don't think there are any more commits to be made for the linked issues.
I'd be working on #4 once this PR is reviewed

**Comment by ArunTeltia** [comment]
Okay then I will reviewing this PR

**Comment by ArunTeltia** [comment]
I tested this and i dont think there are any bugs @singhayushh, thank you for your precious PR🙌
@LordShenron can you merge this PR

**Review by ArunTeltia — APPROVED** [review]

**Comment by singhayushh** [comment]
Thanks a lot!

Also, while going through the application, I found some issues and bugs. Shall I raise issues for each of them?

**Comment by ArunTeltia** [comment]
If you want to work on this then yes you can raise issues and work on it, 
Raising issue will make the project a little more maintained and we can work on the priority of the issue as well 🚀

**Pull request merged**
